# permissions for end users to view gamesessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gamesession-viewer-role
rules:
- apiGroups:
  - gamesession.kube-game.shiftweek.poc
  resources:
  - gamesessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gamesession.kube-game.shiftweek.poc
  resources:
  - gamesessions/status
  verbs:
  - get
