---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for gamesession.kube-game.shiftweek.poc/v1alpha1, Kind: GameSession
  ##
  - apiGroups:
      - gamesession.kube-game.shiftweek.poc
    resources:
      - gamesessions
      - gamesessions/status
      - gamesessions/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for gamesession.kube-game.shiftweek.poc/v1alpha1, Kind: PlayerMove
  ##
  - apiGroups:
      - gamesession.kube-game.shiftweek.poc
    resources:
      - playermoves
      - playermoves/status
      - playermoves/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
