---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubestonecards.gamesession.kube-game.shiftweek.poc
spec:
  group: gamesession.kube-game.shiftweek.poc
  names:
    kind: KubeStoneCard
    listKind: KubeStoneCardList
    plural: kubestonecards
    singular: kubestonecard
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KubeStoneCard is the Schema for the kubestonecards API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KubeStoneCard
            type: object
            properties:
              image_url:
                type: string
              cost:
                type: number
              value:
                type: number
              name:
                type: string
              deployment_name:
                type: string
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of KubeStoneCard
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
