---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gamesessions.gamesession.kube-game.shiftweek.poc
spec:
  group: gamesession.kube-game.shiftweek.poc
  names:
    kind: GameSession
    listKind: GameSessionList
    plural: gamesessions
    singular: gamesession
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GameSession is the Schema for the gamesessions API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of GameSession
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of GameSession
            type: object
            properties:
              p1HP:
                description: Player 1 health points
                type: integer
                minimum: 0
                default: 20
              p2HP:
                description: Player 2 health points
                type: integer
                minimum: 0
                default: 20
              p1AP:
                description: Player 1 armor points
                type: integer
                minimum: 0
                default: 0
              p2AP:
                description: Player 2 armor points
                type: integer
                minimum: 0
                default: 0
              p1MP:
                description: Player 1 mana points
                type: integer
                minimum: 0
                default: 5
              p2MP:
                description: Player 2 mana points
                type: integer
                minimum: 0
                default: 5
              p1HandSize:
                description: Player 1 hand size 
                type: integer
                minimum: 0
              p2HandSize:
                description: Player 2 hand size 
                type: integer
                minimum: 0
              activePlayer:
                description: Player active turn
                type: string
                default: p1
                enum:
                  - p1
                  - p2
              isSetup:
                type: boolean
                default: false
              p1KubeConfig:
                type: string
              p2KubeConfig:
                type: string
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
